### ISSUE TITLE
Uses TotalPrice instead of TransactionAmount which causes issues when Gift Cards are used.

### ISSUE THREAD

**Issue by prjseal** [vendrcontrib/vendr-payment-provider-square#3]
https://github.com/vendrcontrib/vendr-payment-provider-square/blob/6a3d8a2b4630e792dfad3a570d7ff6ec05cdb5f3/src/Vendr.Contrib.PaymentProviders.Square/SquareCheckoutOnetimePaymentProvider.cs#L95

As per the title, this above linked line uses TotalPrice instead of TransactionAmount which causes issues when Gift Cards are used.

**Comment by mattbrailsford** [comment]
Fixed in this commit https://github.com/vendrcontrib/vendr-payment-provider-square/commit/0703a6630812cea5dc1f280a42f37299a3cda848

You can get a build of this package from the unstable feed here https://outfielddigital.pkgs.visualstudio.com/vendr-contrib-public/_packaging/vendr-contrib-unstable/nuget/v3/index.json

Feel free to test and see if it works as expected

**Comment by prjseal** [comment]
yeah that works, thanks

**Comment by prjseal** [comment]
Hi @mattbrailsford 
Whilst this works, if someone pays using a gift card and pays the difference they are receiving a payment error email.
I'm not sure where in the pipeline this error is occurring. Could there be a check somewhere that checks the amount paid against the total amount and returns an error if they don't match because of a gift card amount?

**Comment by mattbrailsford** [comment]
Looks like we missed this line needing updating https://github.com/vendrcontrib/vendr-payment-provider-square/blob/dev/src/Vendr.Contrib.PaymentProviders.Square/SquareCheckoutOnetimePaymentProvider.cs#L207

it’ll currently be recording an authorised amount pre-gift cards so Vendr thinks the customer has been overcharged.
